HTTP benchmark task
nikoncode/go-ht pull request #4
Opened 2019-03-06 23:22 UTC by nikoncode

FYI @kortelyov

2019-03-07 06:21 UTC, kortelyov reviewed
Main task still doesn't complete

2019-03-07 06:32 UTC, kortelyov requested changes
default output
{min:665978007 max:1193735215 avg:9.6014168299e+08 timeouts:0}
what does it mean ?

Also I wrote about some URLs (1-...), and we should got separated stats for all of them

2019-03-07 06:32 UTC, kortelyov commented on http_benchmark/main.go
> +		go func() {
don't use anonymous functions

2019-03-07 06:32 UTC, kortelyov commented on http_benchmark/main.go
> +			_, err := client.Get(url)
where is err check?

2019-03-07 06:33 UTC, kortelyov commented on http_benchmark/main.go
> +		go func() {
also add wg pointer to the goroutine's args

2019-03-19 19:55 UTC, nikoncode commented
@kortelyov please review again.

2019-04-01 06:34 UTC, kortelyov approved these changes

2019-04-13 19:23 UTC, merged